language: node_js

sudo: false
dist: trusty

node_js:
  - '8'
  - '9'
  - '10'

branches:
  only:
  - master
  - starter-kit
  - demo

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - npm i -g npm@latest

install:
  - travis_retry npm i
  - npm install -g codecov

before_script:

script:
  - npm run lint:ci
  - npm run build:prod
  - istanbul cover ./node_modules/jasmine/bin/jasmine.js
  - codecov

git:
  depth: 1
